stages:
  - Webapp build
  - Webapp test
  - Component tests
  - E2E Test
cache:
  paths:
    - .yarn
    - node_modules/
Yarn build:
  image: node:18.4.0
  stage: Webapp build
  needs: []
  script:
    - cd client
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn build
  retry: 1
Prettier check:
  image: node:18.4.0
  stage: Webapp test
  needs: [Yarn build]
  script:
    - cd client
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn lint:prettier
  retry: 1
Eslint:
  image: node:18.4.0
  stage: Webapp test
  needs: [Yarn build]
  script:
    - cd client
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn lint
  retry: 1
Vitest:
  image: node:18.4.0
  stage: Component tests
  needs: [Yarn build]
  script:
    - cd client
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn test --passWithNoTests
  retry: 2
Cypress e2e test:
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  stage: E2E Test
  script:
    - cd client
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn dev --host &
    - npx cypress run --browser chrome
