stages:
  - Webapp build
  - Webapp test
  - E2E Testing
cache:
  paths:
    - .yarn
    - node_modules/
Yarn Build:
  image: node:18.4.0
  stage: Webapp build
  needs: []
  script:
    - cd client
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn build
  retry: 1
Prettier check:
  image: node:18.4.0
  stage: Webapp test
  needs: [Yarn Build]
  script:
    - cd client
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn lint:prettier
  retry: 1
Eslint:
  image: node:18.4.0
  stage: Webapp test
  needs: [Yarn Build]
  script:
    - cd client
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn lint
  retry: 1

E2E Testing:
  image: node:18.4.0
  stage: E2E Testing
  script:
    - cd server
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn build:server
    - yarn dev:server
    - cd ../client
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn dev
    - yarn e2e
