stages:
  - Webapp build
  - Webapp test
  - E2E Test
cache:
  paths:
    - .yarn
    - node_modules/
Yarn Build:
  image: node:18.4.0
  stage: Webapp build
  needs: []
  script:
    - cd client
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn build
  retry: 1
Prettier check:
  image: node:18.4.0
  stage: Webapp test
  needs: [Yarn Build]
  script:
    - cd client
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn lint:prettier
  retry: 1
Eslint:
  image: node:18.4.0
  stage: Webapp test
  needs: [Yarn Build]
  script:
    - cd client
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn lint
  retry: 1

E2E Test:
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  stage: Client test
  script:
    - cd client
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn dev &
    - yarn cypress run --browser chrome
