export const drinks = [
  {
    id: '15997',
    name: 'GG',
    category: 'Ordinary Drink',
    alcoholic: true,
    glass: 'Collins Glass',
    instructions:
      'Pour the Galliano liqueur over ice. Fill the remainder of the glass with ginger ale and thats all there is to it. You now have a your very own GG.',
    strInstructionsES: null,
    strInstructionsDE:
      'Den Galliano-Likör über Eis gießen. Füllen Sie den Rest des Glases mit Ginger Ale und das ist alles, was dazu gehört. Du hast jetzt ein eigenes GG.',
    strInstructionsFR: null,
    strInstructionsIT:
      'Versare il liquore Galliano su ghiaccio.\r\nRiempi il resto del bicchiere con ginger ale e questo è tutto.\r\nOra hai il tuo GG personale.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg',
    ingredients: [
      {
        ingredient: 'Galliano',
        measure: '2 1/2 shots ',
      },
      {
        ingredient: 'Ginger ale',
      },
      {
        ingredient: 'Ice',
      },
    ],
  },
  {
    id: '17222',
    name: 'A1',
    category: 'Cocktail',
    alcoholic: true,
    glass: 'Cocktail glass',
    instructions:
      'Pour all ingredients into a cocktail shaker, mix and serve over ice into a chilled glass.',
    strInstructionsES:
      'Vierta todos los ingredientes en una coctelera, mezcle y sirva con hielo en un vaso frío.',
    strInstructionsDE:
      'Alle Zutaten in einen Cocktailshaker geben, mischen und über Eis in ein gekühltes Glas servieren.',
    strInstructionsFR: null,
    strInstructionsIT:
      'Versare tutti gli ingredienti in uno shaker, mescolare e servire con ghiaccio in un bicchiere freddo.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg',
    ingredients: [
      { ingredient: 'Gin', measure: '1 3/4 shot ' },
      { ingredient: 'Grand Marnier', measure: '1 Shot ' },
      { ingredient: 'Lemon Juice', measure: '1/4 Shot' },
      { ingredient: 'Grenadine', measure: '1/8 Shot' },
    ],
  },
  {
    id: '17225',
    name: 'Ace',
    category: 'Cocktail',
    alcoholic: true,
    glass: 'Martini Glass',
    instructions:
      'Shake all the ingredients in a cocktail shaker and ice then strain in a cold glass.',
    strInstructionsES:
      'Agite todos los ingredientes en una coctelera con hielo y entonces cuélelos sobre un vaso enfriado.',
    strInstructionsDE:
      'Alle Zutaten in einem Cocktailshaker mit Eis schütteln und dann in einem kalten Glas abseihen.',
    strInstructionsFR: null,
    strInstructionsIT:
      'Shakerare tutti gli ingredienti in uno shaker e ghiaccio, quindi filtrare in un bicchiere freddo.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg',
    ingredients: [
      { ingredient: 'Gin', measure: '2 shots ' },
      { ingredient: 'Grenadine', measure: '1/2 shot ' },
      { ingredient: 'Heavy cream', measure: '1/2 shot ' },
      { ingredient: 'Milk', measure: '1/2 shot' },
      { ingredient: 'Egg White', measure: '1/2 Fresh' },
    ],
  },
  {
    id: '14229',
    name: '747',
    category: 'Shot',
    alcoholic: true,
    glass: 'Shot glass',
    instructions:
      'pour kaluha, then Baileys, then Frangelico not chilled and not layered -- SERVE!!!',
    strInstructionsES: null,
    strInstructionsDE:
      'Gießen Sie kaluha, dann Baileys, dann Frangelico nicht gekühlt und nicht geschichtet -- SERVE!!!!!!!!',
    strInstructionsFR: null,
    strInstructionsIT: 'Versa Kahlua, Baileys e poi Frangelico.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/xxsxqy1472668106.jpg',
    ingredients: [
      { ingredient: 'Kahlua', measure: '1/3 part ' },
      { ingredient: 'Baileys irish cream', measure: '1/3 part ' },
      { ingredient: 'Frangelico', measure: '1/3 part ' },
    ],
  },
  {
    id: '17203',
    name: 'Kir',
    category: 'Ordinary Drink',
    alcoholic: true,
    glass: 'Wine Glass',
    instructions: 'Add the crème de cassis to the bottom of the glass, then top up with wine.',
    strInstructionsES: null,
    strInstructionsDE: 'Gib die Creme de Cassis auf den Boden des Glases und füge dann Wein hinzu.',
    strInstructionsFR: null,
    strInstructionsIT:
      'Aggiungere la crème de cassis sul fondo del bicchiere, quindi rabboccare con il vino.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/apneom1504370294.jpg',
    ingredients: [
      { ingredient: 'Creme de Cassis', measure: '1 part ' },
      { ingredient: 'Champagne', measure: '5 parts ' },
    ],
  },
  {
    id: '13501',
    name: 'ABC',
    category: 'Shot',
    alcoholic: true,
    glass: 'Shot glass',
    instructions: 'Layered in a shot glass.',
    strInstructionsES: 'Coloque todos los ingredientes en un vaso de chupito.',
    strInstructionsDE: 'Schichtaufbau in einem Schnapsglas.',
    strInstructionsFR: null,
    strInstructionsIT:
      "Versa in ordine di lettera i vari ingredienti. 1/3 del bicchiere va riempito con l'Amaretto, 1/3 di Baileys e il restante di Cognac.",
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg',
    ingredients: [
      { ingredient: 'Amaretto', measure: '1/3 ' },
      { ingredient: 'Baileys irish cream', measure: '1/3 ' },
      { ingredient: 'Cognac', measure: '1/3 ' },
    ],
  },
  {
    id: '15288',
    name: '252',
    category: 'Shot',
    alcoholic: true,
    glass: 'Shot glass',
    instructions: 'Add both ingredients to shot glass, shoot, and get drunk quick',
    strInstructionsES: null,
    strInstructionsDE: 'Beide Zutaten in ein Schnapsglas geben.',
    strInstructionsFR: null,
    strInstructionsIT:
      'Aggiungi entrambi gli ingredienti al bicchierino, bevi e ubriacati velocemente',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/rtpxqw1468877562.jpg',
    ingredients: [
      { ingredient: '151 proof rum', measure: '1/2 shot Bacardi ' },
      { ingredient: 'Wild Turkey', measure: '1/2 shot ' },
    ],
  },
  {
    id: '13938',
    name: 'AT&T',
    category: 'Ordinary Drink',
    alcoholic: true,
    glass: 'Highball Glass',
    instructions: 'Pour Vodka and Gin over ice, add Tonic and Stir',
    strInstructionsES: 'Vierta el vodka y la ginebra sobre el hielo, agregue la tónica y revuelva.',
    strInstructionsDE: 'Wodka und Gin über das Eis gießen, Tonic hinzufügen und umrühren.',
    strInstructionsFR: null,
    strInstructionsIT:
      "Versare la vodka e il gin sul ghiaccio, aggiungere l'acqua tonica e mescolare",
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/rhhwmp1493067619.jpg',
    ingredients: [
      { ingredient: 'Absolut Vodka', measure: '1 oz ' },
      { ingredient: 'Gin', measure: '1 oz ' },
      { ingredient: 'Tonic water', measure: '4 oz ' },
    ],
  },
  {
    id: '17141',
    name: 'Smut',
    category: 'Punch / Party Drink',
    alcoholic: true,
    glass: 'Beer mug',
    instructions: 'Throw it all together and serve real cold.',
    strInstructionsES: null,
    strInstructionsDE: 'Schütte alles zusammen und serviere es kalt.',
    strInstructionsFR: null,
    strInstructionsIT: 'Metti tutto insieme e servi freddo.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/rx8k8e1504365812.jpg',
    ingredients: [
      { ingredient: 'Red wine', measure: '1/3 part' },
      { ingredient: 'Peach schnapps', measure: '1 shot' },
      { ingredient: 'Red wine', measure: '1/3 part' },
      { ingredient: 'Orange juice', measure: '1/3 part' },
    ],
  },
  {
    id: '13332',
    name: 'B-53',
    category: 'Shot',
    alcoholic: true,
    glass: 'Collins Glass',
    instructions:
      'Layer the Kahlua, Sambucca and Grand Marnier into a shot glas in that order. Better than B-52',
    strInstructionsES: null,
    strInstructionsDE:
      'Schichte die Kahlua, Sambucca und Grand Marnier in dieser Reihenfolge in ein Schnapsglas ein. Besser als B-52',
    strInstructionsFR: null,
    strInstructionsIT: "Metti Kahlua, Sambuca e Grand Marnier in un bicchierino in quest'ordine. ",
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/rwqxrv1461866023.jpg',
    ingredients: [
      {
        ingredient: 'Kahlua',
        measure: '1/3 shot ',
      },
      {
        ingredient: 'Sambuca',
        measure: '1/3 shot ',
      },
      {
        ingredient: 'Grand Marnier',
        measure: '1/3 shot ',
      },
    ],
  },
  {
    id: '17837',
    name: 'Adam',
    category: 'Ordinary Drink',
    alcoholic: true,
    glass: 'Cocktail glass',
    instructions:
      'In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.',
    strInstructionsES:
      'Mezclar todos los ingredientes en una coctelera con cubitos de hielo hasta la mitad. Agitar bien. Colar el contenido en un vaso de cóctel.',
    strInstructionsDE:
      'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Cocktailglas abseihen.',
    strInstructionsFR: null,
    strInstructionsIT:
      'In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Agitare bene.Filtrare in un bicchiere da cocktail.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/v0at4i1582478473.jpg',
    ingredients: [
      { ingredient: 'Dark rum', measure: '2 oz ' },
      { ingredient: 'Lemon juice', measure: '1 oz ' },
      { ingredient: 'Grenadine', measure: '1 tsp ' },
    ],
  },
  {
    id: '11007',
    name: 'Margarita',
    category: 'Ordinary Drink',
    alcoholic: true,
    glass: 'Cocktail glass',
    instructions:
      'Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.',
    strInstructionsES: null,
    strInstructionsDE:
      'Reiben Sie den Rand des Glases mit der Limettenscheibe, damit das Salz daran haftet. Achten Sie darauf, dass nur der äußere Rand angefeuchtet wird und streuen Sie das Salz darauf. Das Salz sollte sich auf den Lippen des Genießers befinden und niemals in den Cocktail einmischen. Die anderen Zutaten mit Eis schütteln und vorsichtig in das Glas geben.',
    strInstructionsFR: null,
    strInstructionsIT:
      'Strofina il bordo del bicchiere con la fetta di lime per far aderire il sale.\r\nAvere cura di inumidire solo il bordo esterno e cospargere di sale.\r\nIl sale dovrebbe presentarsi alle labbra del bevitore e non mescolarsi mai al cocktail.\r\nShakerare gli altri ingredienti con ghiaccio, quindi versarli delicatamente nel bicchiere.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/5noda61589575158.jpg',
    ingredients: [
      { ingredient: 'Tequila', measure: '1 1/2 oz ' },
      { ingredient: 'Triple sec', measure: '1/2 oz ' },
      { ingredient: 'Lime juice', measure: '1 oz ' },
      { ingredient: 'Salt' },
    ],
  },
  {
    id: '178365',
    name: 'Gin Tonic',
    category: 'Cocktail',
    alcoholic: true,
    glass: 'Highball glass',
    instructions:
      'Fill a highball glass with ice, pour the gin, top with tonic water and squeeze a lemon wedge and garnish with a lemon wedge.',
    strInstructionsES: null,
    strInstructionsDE:
      'Füllen Sie ein Highball-Glas mit Eis, gießen Sie den Gin ein, gießen Sie Tonic Water darüber und drücken Sie eine Zitronenscheibe aus und garnieren Sie sie mit einer Zitronenscheibe.',
    strInstructionsFR: null,
    strInstructionsIT:
      'Colmate un bicchiere highball di ghiaccio, versate il gin, colmate con acqua tonica e spremete uno spicchio di limone e guarnite con una fetta di limone. ',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/qcgz0t1643821443.jpg',
    ingredients: [
      { ingredient: 'Gin', measure: '4 cl' },
      { ingredient: 'Tonic Water', measure: '10 cl' },
      { ingredient: 'Lemon Peel', measure: '1 Slice' },
      { ingredient: 'Ice', measure: 'cubes' },
    ],
  },
  {
    id: '11000',
    name: 'Mojito',
    strDrinkAlternate: null,
    strTags: 'IBA,ContemporaryClassictrueUSA,Asia,Vegan,Citrus,Brunch,Hangover,Mild',
    strVideo: null,
    category: 'Cocktail',
    strIBA: 'Contemporary Classics',
    alcoholic: true,
    glass: 'Highball glass',
    instructions:
      'Muddle mint leaves with sugar and lime juice. Add a splash of soda water and fill the glass with cracked ice. Pour the rum and top with soda water. Garnish and serve with straw.',
    strInstructionsES: null,
    strInstructionsDE:
      'Minzblätter mit Zucker und Limettensaft verrühren. Füge einen Spritzer Sodawasser hinzu und fülle das Glas mit gebrochenem Eis. Den Rum eingießen und mit Sodawasser übergießen. Garnieren und mit einem Strohhalm servieren.',
    strInstructionsFR: null,
    strInstructionsIT:
      'Pestare le foglie di menta con lo zucchero e il succo di lime.\r\nAggiungere una spruzzata di acqua di seltz e riempi il bicchiere con ghiaccio tritato.\r\nVersare il rum e riempire con acqua di seltz.\r\nGuarnire con una fetta di lime, servire con una cannuccia.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/metwgh1606770327.jpg',
    ingredients: [
      { ingredient: 'Light rum', measure: '2-3 oz ' },
      { ingredient: 'Lime', measure: 'Juice of 1 ' },
      { ingredient: 'Sugar', measure: '2 tsp ' },
      { ingredient: 'Mint', measure: '2-4 ' },
      { ingredient: 'Soda water' },
    ],
  },
  {
    id: '11005',
    name: 'Dry Martini',
    strDrinkAlternate: null,
    strTags: 'IBA,Classic,Christmastrue',
    strVideo: null,
    category: 'Cocktail',
    strIBA: 'Unforgettables',
    alcoholic: true,
    glass: 'Cocktail glass',
    instructions:
      'Straight: Pour all ingredients into mixing glass with ice cubes. Stir well. Strain in chilled martini cocktail glass. Squeeze oil from lemon peel onto the drink, or garnish with olive.',
    strInstructionsES: null,
    strInstructionsDE: null,
    strInstructionsFR: null,
    strInstructionsIT:
      "Dritto: Versare tutti gli ingredienti nel mixing glass con cubetti di ghiaccio. Mescolare bene. Filtrare in una coppetta da cocktail Martini ghiacciata. Spremi l'olio della scorza di limone sulla bevanda o guarnisci con l'oliva.",
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/6ck9yi1589574317.jpg',
    ingredients: [
      { ingredient: 'Gin', measure: '1 2/3 oz ' },
      { ingredient: 'Dry Vermouth', measure: '1/3 oz ' },
      { ingredient: 'Olive', measure: '1 ' },
    ],
  },
  {
    id: '11003',
    name: 'Negroni',
    strDrinkAlternate: null,
    strTags: 'IBA,Classic',
    strVideo: 'https://www.youtube.com/watch?v=Y4LH0FQlU8Q',
    category: 'Ordinary Drink',
    strIBA: 'Unforgettables',
    alcoholic: true,
    glass: 'Old-fashioned glass',
    instructions: 'Stir into glass over ice, garnish and serve.',
    strInstructionsES: null,
    strInstructionsDE: 'In ein Glas über das Eis gießen, garnieren und servieren.',
    strInstructionsFR: null,
    strInstructionsIT: 'Mescolare nel bicchiere con ghiaccio, guarnire e servire.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/qgdu971561574065.jpg',
    ingredients: [
      { ingredient: 'Gin', measure: '1 oz ' },
      { ingredient: 'Campari', measure: '1 oz ' },
      { ingredient: 'Sweet Vermouth', measure: '1 oz ' },
    ],
  },
  {
    id: '11006',
    name: 'Daiquiri',
    strDrinkAlternate: null,
    strTags: 'IBA,Classic,Beach',
    strVideo: null,
    category: 'Ordinary Drink',
    strIBA: null,
    alcoholic: true,
    glass: 'Cocktail glass',
    instructions:
      'Pour all ingredients into shaker with ice cubes. Shake well. Strain in chilled cocktail glass.',
    strInstructionsES: null,
    strInstructionsDE:
      'Alle Zutaten in den Shaker mit Eiswürfel geben. Gut schütteln. In einem gekühlten Cocktailglas abseihen.',
    strInstructionsFR: null,
    strInstructionsIT:
      'Versare tutti gli ingredienti nello shaker con cubetti di ghiaccio.Filtrare in una coppetta da cocktail ghiacciata. Agitare bene',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/mrz9091589574515.jpg',
    ingredients: [
      { ingredient: 'Light rum', measure: '1 1/2 oz ' },
      { ingredient: 'Lime', measure: 'Juice of 1/2 ' },
      { ingredient: 'Powdered sugar', measure: '1 tsp ' },
    ],
  },
  {
    id: '11004',
    name: 'Whiskey Sour',
    strDrinkAlternate: null,
    strTags: 'IBA,ClassictrueContemporaryClassic',
    strVideo: 'https://www.youtube.com/watch?v=hFKZPzfngcU',
    category: 'Ordinary Drink',
    strIBA: 'Unforgettables',
    alcoholic: true,
    glass: 'Old-fashioned glass',
    instructions:
      "Shake with ice. Strain into chilled glass, garnish and serve. If served 'On the rocks', strain ingredients into old-fashioned glass filled with ice.",
    strInstructionsES: null,
    strInstructionsDE:
      'Mit Eis schütteln. In ein gekühltes Glas abseihen, garnieren und servieren. Wenn Sie "On the rocks" servieren, die Zutaten in ein old-fashioned, mit Eis gefülltes Glas geben.',
    strInstructionsFR: null,
    strInstructionsIT:
      'Shakerare con ghiaccio. Filtrare in un bicchiere freddo, guarnire e servire.Se servito "On the rocks", filtra gli ingredienti in un bicchiere vecchio stile pieno di ghiaccio.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/hbkfsh1589574990.jpg',
    ingredients: [
      { ingredient: 'Blended whiskey', measure: '2 oz ' },
      { ingredient: 'Lemon', measure: 'Juice of 1/2 ' },
      { ingredient: 'Powdered sugar', measure: '1/2 tsp ' },
      { ingredient: 'Cherry', measure: '1 ' },
      { ingredient: 'Lemon', measure: '1/2 slice ' },
    ],
  },
  {
    id: '17204',
    name: 'Long Island Iced Tea',
    strDrinkAlternate: null,
    strTags: 'IBA,ContemporaryClassic',
    strVideo: null,
    category: 'Ordinary Drink',
    strIBA: 'Contemporary Classics',
    alcoholic: true,
    glass: 'Highball glass',
    instructions:
      'Mix all contents in a highball glass and sitr gently. Add dash of Coca-Cola for the coloring and garnish with lemon or lime twist.',
    strInstructionsES: null,
    strInstructionsDE:
      'Den gesamten Inhalt in einem Highball-Glas mischen und vorsichtig umrühren. Für die Farbgebung einen Schuss Coca-Cola hinzufügen und mit Zitronen- oder Limettenspirale garnieren.',
    strInstructionsFR: null,
    strInstructionsIT:
      'Mescolare tutto il contenuto in un bicchiere highball e mescolare delicatamente.\r\nAggiungere un pizzico di Coca-Cola per la colorazione e guarnire con una scorza di limone o lime.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/wx7hsg1504370510.jpg',
    ingredients: [
      { ingredient: 'Vodka', measure: '1/2 oz ' },
      { ingredient: 'Light rum', measure: '1/2 oz ' },
      { ingredient: 'Gin', measure: '1/2 oz ' },
      { ingredient: 'Tequila', measure: '1/2 oz ' },
      { ingredient: 'Triple sec', measure: '1/2 oz' },
      { ingredient: 'Lemon', measure: 'Juice of 1/2 ' },
      { ingredient: 'Coca-Cola' },
    ],
  },
  {
    id: '11001',
    name: 'Old Fashioned',
    strDrinkAlternate: null,
    strTags: 'IBA,ClassictrueExpensive,Savory',
    strVideo: 'https://www.youtube.com/watch?v=YsE_igrPXZs',
    category: 'Cocktail',
    strIBA: 'Unforgettables',
    alcoholic: true,
    glass: 'Old-fashioned glass',
    instructions:
      'Place sugar cube in old fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolved.\r\nFill the glass with ice cubes and add whiskey.\r\n\r\nGarnish with orange twist, and a cocktail cherry.',
    strInstructionsES: null,
    strInstructionsDE:
      'Zuckerwürfel in ein old fashioned Glas geben und mit Bitterstoff sättigen, einen Schuss Wasser hinzufügen. Vermischen, bis sie sich auflösen.',
    strInstructionsFR: null,
    strInstructionsIT:
      "Mettere la zolletta di zucchero nel bicchiere vecchio stile e saturare con il bitter, aggiungere un goccio di acqua naturale.\r\nPestare finché non si scioglie.\r\nRiempi il bicchiere con cubetti di ghiaccio e aggiungi il whisky.\r\nGuarnire con una scorza d'arancia e una ciliegina al maraschino.",
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg',
    ingredients: [
      { ingredient: 'Bourbon', measure: '4.5 cL' },
      { ingredient: 'Angostura bitters', measure: '2 dashes' },
      { ingredient: 'Sugar', measure: '1 cube' },
      { ingredient: 'Water', measure: 'dash' },
    ],
  },
  {
    id: '12402',
    name: 'Tom Collins',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    category: 'Ordinary Drink',
    strIBA: null,
    alcoholic: true,
    glass: 'Collins glass',
    instructions:
      'In a shaker half-filled with ice cubes, combine the gin, lemon juice, and sugar. Shake well. Strain into a collins glass alomst filled with ice cubes. Add the club soda. Stir and garnish with the cherry and the orange slice.',
    strInstructionsES: null,
    strInstructionsDE:
      'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, Gin, Zitronensaft und Zucker mischen. Gut schütteln. In ein Collins-Glas abseihen, das mit Eiswürfeln gefüllt ist. Füge das Club-Soda hinzu. Umrühren und mit der Kirsche und der Orangenscheibe garnieren.',
    strInstructionsFR: null,
    strInstructionsIT:
      "In uno shaker riempito a metà con cubetti di ghiaccio, unisci il gin, il succo di limone e lo zucchero.Mescolate e guarnite con la ciliegia e la fetta d'arancia.Filtrare in un bicchiere collins pieno di cubetti di ghiaccio.Aggiungi la soda club.Agitare bene.",
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/7cll921606854636.jpg',
    ingredients: [
      { ingredient: 'Gin', measure: '2 oz ' },
      { ingredient: 'Lemon juice', measure: '1 oz ' },
      { ingredient: 'Sugar', measure: '1 tsp superfine ' },
      { ingredient: 'Club soda', measure: '3 oz ' },
      { ingredient: 'Maraschino cherry', measure: '1 ' },
      { ingredient: 'Orange', measure: '1 slice' },
    ],
  },
  {
    id: '11288',
    name: 'Cuba Libre',
    strDrinkAlternate: null,
    strTags: 'IBA,ContemporaryClassic',
    strVideo: null,
    category: 'Ordinary Drink',
    strIBA: 'Contemporary Classics',
    alcoholic: true,
    glass: 'Highball glass',
    instructions:
      'Build all ingredients in a Collins glass filled with ice. Garnish with lime wedge.',
    strInstructionsES: null,
    strInstructionsDE:
      'Geben Sie alle Zutaten in ein mit Eis gefülltes Collins-Glas. Mit Limettenkeil garnieren.',
    strInstructionsFR: null,
    strInstructionsIT:
      'Mettere tutti gli ingredienti in un bicchiere Collins pieno di ghiaccio. Guarnire con uno spicchio di lime.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/wmkbfj1606853905.jpg',
    ingredients: [
      { ingredient: 'Light rum', measure: '2 oz ' },
      { ingredient: 'Lime', measure: 'Juice of 1/2 ' },
      { ingredient: 'Coca-Cola' },
    ],
  },
  {
    id: '17212',
    name: 'Espresso Martini',
    strDrinkAlternate: null,
    strTags: 'IBA,NewEra',
    strVideo: null,
    category: 'Cocktail',
    strIBA: 'New Era Drinks',
    alcoholic: true,
    glass: 'Cocktail glass',
    instructions:
      'Pour ingredients into shaker filled with ice, shake vigorously, and strain into chilled martini glass',
    strInstructionsES: null,
    strInstructionsDE:
      'Zutaten in einen mit Eis gefüllten Shaker geben, kräftig schütteln und in ein gekühltes Martini-Glas abseihen.',
    strInstructionsFR: null,
    strInstructionsIT:
      'Versare gli ingredienti in uno shaker pieno di ghiaccio, shakerare energicamente e filtrare in un bicchiere da martini freddo',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    picture: 'https://www.thecocktaildb.com/images/media/drink/n0sx531504372951.jpg',
    ingredients: [
      { ingredient: 'Vodka', measure: '4 cl' },
      { ingredient: 'Kahlua', measure: '3 cl' },
      { ingredient: 'Simple syrup', measure: '1 dash' },
      { ingredient: 'Espresso', measure: '1 double shot' },
    ],
  },
]
