import json

transformed_data = []
data = {
    "drinks": [
        
{
"idDrink": "17215",
"strDrink": "Spritz",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Ordinary Drink",
"strIBA": "New Era Drinks",
"strAlcoholic": "Alcoholic",
"strGlass": "Old-Fashioned glass",
"strInstructions": "Build into glass over ice, garnish and serve.",
"strInstructionsES": None,
"strInstructionsDE": "Über Eis in Glas einfüllen, garnieren und servieren.",
"strInstructionsFR": None,
"strInstructionsIT": "Build into glass over ice, garnish and serve.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/j9evx11504373665.jpg",
"strIngredient1": "Prosecco",
"strIngredient2": "Campari",
"strIngredient3": "Soda Water",
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "6 cl",
"strMeasure2": "4 cl",
"strMeasure3": "splash",
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-09-02 18:34:25"
},
{
"idDrink": "12130",
"strDrink": "Scooter",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Ordinary Drink",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Cocktail glass",
"strInstructions": "Shake all ingredients well with cracked ice, strain into a cocktail glass, and serve.",
"strInstructionsES": None,
"strInstructionsDE": "Alle Zutaten gut mit gebrochenem Eis schütteln, in ein Cocktailglas abseihen und servieren.",
"strInstructionsFR": None,
"strInstructionsIT": "Shakerare bene tutti gli ingredienti con ghiaccio tritato, filtrare in una coppetta da cocktail e servire.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/twuptu1483388307.jpg",
"strIngredient1": "Brandy",
"strIngredient2": "Amaretto",
"strIngredient3": "Light cream",
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 oz ",
"strMeasure2": "1 oz ",
"strMeasure3": "1 oz ",
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-01-02 20:18:27"
},
{
"idDrink": "13020",
"strDrink": "Sangria",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Punch / Party Drink",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Pitcher",
"strInstructions": "Mix all together in a pitcher and refrigerate. Add cloves and cinnamon sticks to taste. Serve in wine glasses.",
"strInstructionsES": None,
"strInstructionsDE": "Alles in einem Krug vermischen und im Kühlschrank aufbewahren. Nach Belieben Nelken und Zimtstangen hinzufügen. In Weingläsern servieren.",
"strInstructionsFR": None,
"strInstructionsIT": "Mescolare il tutto in una brocca e conservare in frigorifero.\r\nAggiungere i chiodi di garofano e le stecche di cannella a piacere.\r\nServire in calici da vino.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xrvxpp1441249280.jpg",
"strIngredient1": "Red wine",
"strIngredient2": "Sugar",
"strIngredient3": "Orange juice",
"strIngredient4": "Lemon juice",
"strIngredient5": "Cloves",
"strIngredient6": "Cinnamon",
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 bottle ",
"strMeasure2": "1/2 cup ",
"strMeasure3": "1 cup ",
"strMeasure4": "1 cup ",
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2015-09-03 04:01:20"
},
{
"idDrink": "17193",
"strDrink": "Stinger",
"strDrinkAlternate": None,
"strTags": "IBA,Classic",
"strVideo": None,
"strCategory": "Ordinary Drink",
"strIBA": "Unforgettables",
"strAlcoholic": "Alcoholic",
"strGlass": "Cocktail glass",
"strInstructions": "Pour in a mixing glass with ice, stir and strain into a cocktail glass. May also be served on rocks in a rocks glass.",
"strInstructionsES": None,
"strInstructionsDE": "In ein Mischglas mit Eis geben, umrühren und in ein Cocktailglas abseihen. Kann auch auf Eiswürfeln in einem Steinglas serviert werden.",
"strInstructionsFR": None,
"strInstructionsIT": "Versare in un mixing glass con ghiaccio, mescolare e filtrare in una coppetta da cocktail.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/2ahv791504352433.jpg",
"strIngredient1": "Brandy",
"strIngredient2": "White Creme de Menthe",
"strIngredient3": None,
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 1/2 oz ",
"strMeasure2": "1/2 oz ",
"strMeasure3": None,
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-09-02 12:40:33"
},
{
"idDrink": "12127",
"strDrink": "Sazerac",
"strDrinkAlternate": None,
"strTags": "IBA,Classic",
"strVideo": "https://www.youtube.com/watch?v=RuZzOcjJUYw",
"strCategory": "Ordinary Drink",
"strIBA": "Unforgettables",
"strAlcoholic": "Alcoholic",
"strGlass": "Old-fashioned glass",
"strInstructions": "Rinse a chilled old-fashioned glass with the absinthe, add crushed ice, and set it aside. Stir the remaining ingredients over ice and set it aside. Discard the ice and any excess absinthe from the prepared glass, and strain the drink into the glass. Add the lemon peel for garnish.",
"strInstructionsES": None,
"strInstructionsDE": "Ein gekühltes old-fashioned Glas mit dem Absinth ausspülen, zerstoßenes Eis hinzufügen und beiseite stellen. Die restlichen Zutaten über das Eis geben und beiseite stellen. Entsorgen Sie das Eis und den überschüssigen Absinth aus dem vorbereiteten Glas und seihen Sie das Getränk in das Glas. Die Zitronenschale als Garnierung hinzufügen.",
"strInstructionsFR": None,
"strInstructionsIT": "Sciacquare un bicchiere vecchio stile freddo con l'assenzio, aggiungere il ghiaccio tritato e metterlo da parte. Mescola gli ingredienti rimanenti sul ghiaccio e mettilo da parte. Togli il ghiaccio e l'assenzio in eccesso dal bicchiere precedentemente preparato e filtra la bevanda nel bicchiere .Aggiungere la scorza di limone per guarnire.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vvpxwy1439907208.jpg",
"strIngredient1": "Ricard",
"strIngredient2": "Sugar",
"strIngredient3": "Peychaud bitters",
"strIngredient4": "Water",
"strIngredient5": "Bourbon",
"strIngredient6": "Lemon peel",
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 tsp ",
"strMeasure2": "1/2 tsp superfine ",
"strMeasure3": "2 dashes ",
"strMeasure4": "1 tsp ",
"strMeasure5": "2 oz ",
"strMeasure6": "1 twist of ",
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2015-08-18 15:13:28"
},
{
"idDrink": "12196",
"strDrink": "Sidecar",
"strDrinkAlternate": None,
"strTags": "IBA,Classic",
"strVideo": "https://www.youtube.com/watch?v=uvKKILoO-Nk",
"strCategory": "Ordinary Drink",
"strIBA": "Unforgettables",
"strAlcoholic": "Alcoholic",
"strGlass": "Cocktail glass",
"strInstructions": "Pour all ingredients into cocktail shaker filled with ice. Shake well and strain into cocktail glass.",
"strInstructionsES": None,
"strInstructionsDE": "Alle Zutaten in einen mit Eis gefüllten Cocktailshaker geben. Gut schütteln und in ein Cocktailglas abseihen.",
"strInstructionsFR": None,
"strInstructionsIT": "Versare tutti gli ingredienti in uno shaker pieno di ghiaccio.Shakerare bene e filtrare nella coppetta da cocktail.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/x72sik1606854964.jpg",
"strIngredient1": "Cognac",
"strIngredient2": "Cointreau",
"strIngredient3": "Lemon juice",
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "2 oz ",
"strMeasure2": "1/2 oz ",
"strMeasure3": "1 oz ",
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": "https://www.flickr.com/photos/mstyne/29716525626/in/dateposted/",
"strImageAttribution": "Michael Styne https://www.flickr.com/photos/mstyne/",
"strCreativeCommonsConfirmed": "Yes",
"dateModified": "2015-08-18 15:07:32"
},
{
"idDrink": "178349",
"strDrink": "Snowday",
"strDrinkAlternate": None,
"strTags": "Winter",
"strVideo": None,
"strCategory": "Cocktail",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Collins glass",
"strInstructions": "Stir all ingredients with ice. Strain into a chilled rocks glass over fresh ice. Express orange peel over drink and garnish.",
"strInstructionsES": None,
"strInstructionsDE": None,
"strInstructionsFR": None,
"strInstructionsIT": "Mescola tutti gli ingredienti con il ghiaccio. Filtrare in un bicchiere con dei cubetti di ghiaccio. Spremi la scorza d'arancia sulla bevanda e guarnire.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/4n1ipk1614009624.jpg",
"strIngredient1": "Vodka",
"strIngredient2": "Amaro Montenegro",
"strIngredient3": "Ruby Port",
"strIngredient4": "Blood Orange",
"strIngredient5": "Angostura Bitters",
"strIngredient6": "Orange Peel",
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 oz",
"strMeasure2": "1 oz",
"strMeasure3": "1 oz",
"strMeasure4": "1 tsp",
"strMeasure5": "Dash",
"strMeasure6": "Garnish with",
"strMeasure7": "",
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": "https://www.instagram.com/p/CLkmoNJFXUe/",
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": None
},
{
"idDrink": "178322",
"strDrink": "Spice 75",
"strDrinkAlternate": None,
"strTags": "Christmas",
"strVideo": None,
"strCategory": "Cocktail",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Wine Glass",
"strInstructions": "Gently warm 60g golden caster sugar in a pan with 30ml water and 1 tbsp allspice. Cook gently until the sugar has dissolved, then leave the mixture to cool. Strain through a sieve lined with a coffee filter (or a double layer of kitchen paper).\r\n\r\nPour 60ml of the spiced syrup into a cocktail shaker along with 200ml rum and 90ml lime juice. Shake with ice and strain between six flute glasses. Top up with 600ml champagne and garnish each with an orange twist.",
"strInstructionsES": None,
"strInstructionsDE": None,
"strInstructionsFR": None,
"strInstructionsIT": "Scaldare delicatamente 60 g di zucchero di canna in una padella con 30 ml di acqua e 1 cucchiaio di pimento. Cuocere a fuoco lento finché lo zucchero non si sarà sciolto, quindi lasciare raffreddare il composto. Filtrare al setaccio rivestito con un filtro da caffè (o un doppio strato di carta da cucina) .  Versare 60 ml di sciroppo speziato in uno shaker insieme a 200 ml di rum e 90 ml di succo di lime. Shakerare con ghiaccio e filtrare tra sei bicchieri flute. Riempire con 600 ml di champagne e guarnire ciascuno con un tocco d'arancia.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/0108c41576797064.jpg",
"strIngredient1": "Sugar",
"strIngredient2": "Allspice",
"strIngredient3": "Rum",
"strIngredient4": "Lime Juice",
"strIngredient5": "Champagne",
"strIngredient6": "Orange spiral",
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "60 ml",
"strMeasure2": "1 tblsp",
"strMeasure3": "20 cl",
"strMeasure4": "90 ml",
"strMeasure5": "6 cl",
"strMeasure6": "Garnish with",
"strMeasure7": "",
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": None
},
{
"idDrink": "14195",
"strDrink": "Snowball",
"strDrinkAlternate": None,
"strTags": "Christmas",
"strVideo": None,
"strCategory": "Ordinary Drink",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Highball glass",
"strInstructions": "Place one ice cube in the glass and add 1 1/2 oz of Advocaat. Fill up the glass with lemonade and decorate with a slice of lemon. Serve at once.",
"strInstructionsES": None,
"strInstructionsDE": "Einen Eiswürfel in das Glas geben und 4,5 cl. Advocaat hinzufügen. Das Glas mit Limonade füllen und mit einer Scheibe Zitrone dekorieren. Sofort servieren.",
"strInstructionsFR": None,
"strInstructionsIT": "Riempite il bicchiere con la limonata e decorate con una fetta di limone.\r\n",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/7ibfs61504735416.jpg",
"strIngredient1": "Advocaat",
"strIngredient2": "Lemonade",
"strIngredient3": "Lemon",
"strIngredient4": "Ice",
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 1/2 oz ",
"strMeasure2": "8-10 oz cold ",
"strMeasure3": "1 slice ",
"strMeasure4": "cubes",
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-09-06 23:03:36"
},
{
"idDrink": "16985",
"strDrink": "Shot-gun",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Shot",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Shot glass",
"strInstructions": "Pour one part Jack Daneils and one part Jim Beam into shot glass then float Wild Turkey on top.",
"strInstructionsES": None,
"strInstructionsDE": "Gießen Sie ein Teil Jack Daniels und ein Teil Jim Beam in ein Schnapsglas und lassen Sie Wild Turkey darauf treiben.",
"strInstructionsFR": None,
"strInstructionsIT": "Versare una parte di Jack Daniels e una parte diJim Beam nel bicchierino da shot, infine versare il Wild Turkey.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/2j1m881503563583.jpg",
"strIngredient1": "Jim Beam",
"strIngredient2": "Jack Daniels",
"strIngredient3": "Wild Turkey",
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 part ",
"strMeasure2": "1 part ",
"strMeasure3": "1 oz ",
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-08-24 09:33:03"
},
{
"idDrink": "12107",
"strDrink": "Salty Dog",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Ordinary Drink",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Highball glass",
"strInstructions": "Pour all ingredients over ice cubes in a highball glass. Stir well and serve. (Vodka may be substituted for gin, if preferred.)",
"strInstructionsES": None,
"strInstructionsDE": "Alle Zutaten über Eiswürfel in ein Highball-Glas gießen. Gut umrühren und servieren. (Wodka kann durch Gin ersetzt werden, wenn gewünscht.)",
"strInstructionsFR": None,
"strInstructionsIT": "Versare tutti gli ingredienti sui cubetti di ghiaccio in un bicchiere highball.Mescolate bene e servite.(La vodka può essere sostituita al gin, se si preferisce.)",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/4vfge01504890216.jpg",
"strIngredient1": "Grapefruit juice",
"strIngredient2": "Gin",
"strIngredient3": "Salt",
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "5 oz ",
"strMeasure2": "1 1/2 oz ",
"strMeasure3": "1/4 tsp ",
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-09-08 18:03:36"
},
{
"idDrink": "12308",
"strDrink": "Stone Sour",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Ordinary Drink",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Whiskey sour glass",
"strInstructions": "Shake all ingredients with ice, strain into a chilled whiskey sour glass, and serve.",
"strInstructionsES": None,
"strInstructionsDE": "Alle Zutaten mit Eis schütteln, in ein gekühltes Whiskey-Sourglas abseihen und servieren.",
"strInstructionsFR": None,
"strInstructionsIT": "Shakerare tutti gli ingredienti con ghiaccio, filtrare in un bicchiere ghiacciato di whisky sour e servire.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vruvtp1472719895.jpg",
"strIngredient1": "Apricot brandy",
"strIngredient2": "Orange juice",
"strIngredient3": "Sweet and sour",
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 oz ",
"strMeasure2": "1 oz ",
"strMeasure3": "1 oz ",
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2016-09-01 09:51:35"
},
{
"idDrink": "13377",
"strDrink": "Sea breeze",
"strDrinkAlternate": None,
"strTags": "IBA,ContemporaryClassic",
"strVideo": None,
"strCategory": "Ordinary Drink",
"strIBA": "Contemporary Classics",
"strAlcoholic": "Alcoholic",
"strGlass": "Highball glass",
"strInstructions": "Build all ingredients in a highball glass filled with ice. Garnish with lime wedge.",
"strInstructionsES": None,
"strInstructionsDE": "Alle Zutaten in einem mit Eis gefüllten Highball-Glas vermengen. Mit Limettenkeil garnieren.",
"strInstructionsFR": None,
"strInstructionsIT": "Metti tutti gli ingredienti in un bicchiere highball pieno di ghiaccio.\r\nGuarnire con uno spicchio di lime.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/7rfuks1504371562.jpg",
"strIngredient1": "Vodka",
"strIngredient2": "Cranberry juice",
"strIngredient3": "Grapefruit juice",
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 1/2 oz ",
"strMeasure2": "4 oz ",
"strMeasure3": "1 oz ",
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-09-02 17:59:22"
},
{
"idDrink": "12158",
"strDrink": "Scotch Sour",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Ordinary Drink",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Whiskey sour glass",
"strInstructions": "Shake scotch, juice of lime, and powdered sugar with ice and strain into a whiskey sour glass. Decorate with 1/2 slice lemon, top with the cherry, and serve.",
"strInstructionsES": None,
"strInstructionsDE": "Scotch, Limettensaft und Puderzucker mit Eis schütteln und in ein Whiskey-Sourglas abseihen. Mit 1/2 Scheibe Zitrone dekorieren, mit der Kirsche belegen und servieren.",
"strInstructionsFR": None,
"strInstructionsIT": "Shakerare scotch, succo di lime e zucchero a velo con ghiaccio e filtrare in un bicchiere da whisky sour. Decorare con 1/2 fetta di limone, guarnire con la ciliegia e servire.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/0dnb6k1504890436.jpg",
"strIngredient1": "Scotch",
"strIngredient2": "Lime",
"strIngredient3": "Powdered sugar",
"strIngredient4": "Lemon",
"strIngredient5": "Cherry",
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 1/2 oz ",
"strMeasure2": "Juice of 1/2 ",
"strMeasure3": "1/2 tsp ",
"strMeasure4": "1/2 slice ",
"strMeasure5": "1 ",
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-09-08 18:07:16"
},
{
"idDrink": "16990",
"strDrink": "Sweet Tooth",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Shake",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Highball Glass",
"strInstructions": "Put 2 shots Godiva Liquour into a glass, add as much or as little milk as you would like.",
"strInstructionsES": None,
"strInstructionsDE": "Geben Sie 2 Spritzer Godiva Liquour in ein Glas, geben Sie so viel Milch hinzu, wie Sie möchten.",
"strInstructionsFR": None,
"strInstructionsIT": "Metti 2 shot di Godiva Liqueur in un bicchiere, aggiungi tanto o poco latte quanto desideri.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/j6rq6h1503563821.jpg",
"strIngredient1": "Godiva liqueur",
"strIngredient2": "Milk",
"strIngredient3": None,
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "2 shots ",
"strMeasure2": None,
"strMeasure3": None,
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-08-24 09:37:01"
},
{
"idDrink": "12162",
"strDrink": "Screwdriver",
"strDrinkAlternate": None,
"strTags": "IBA",
"strVideo": "https://www.youtube.com/watch?v=ce_YOgaEo3Q",
"strCategory": "Ordinary Drink",
"strIBA": "Unforgettables",
"strAlcoholic": "Alcoholic",
"strGlass": "Highball glass",
"strInstructions": "Mix in a highball glass with ice. Garnish and serve.",
"strInstructionsES": None,
"strInstructionsDE": "In einem Highball-Glas mit Eis mischen. Garnieren und servieren.",
"strInstructionsFR": None,
"strInstructionsIT": "Mescolare in un bicchiere highball con ghiaccio. Guarnire e servire.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/8xnyke1504352207.jpg",
"strIngredient1": "Vodka",
"strIngredient2": "Orange juice",
"strIngredient3": None,
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "2 oz ",
"strMeasure2": None,
"strMeasure3": None,
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-09-02 12:36:47"
},
{
"idDrink": "12190",
"strDrink": "Sherry Flip",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Ordinary Drink",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Nick and Nora Glass",
"strInstructions": "Shake all ingredients (except nutmeg) with ice and strain into a whiskey sour glass. Sprinkle nutmeg on top and serve.",
"strInstructionsES": None,
"strInstructionsDE": "Alle Zutaten (außer Muskatnuss) mit Eis schütteln und in ein Whiskey-Sourglas abseihen. Muskatnuss darüber streuen und servieren.",
"strInstructionsFR": None,
"strInstructionsIT": "Shakerare tutti gli ingredienti (tranne la noce moscata) con ghiaccio e filtrare in un bicchiere da whisky sour. Cospargere di noce moscata e servire.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/qrryvq1478820428.jpg",
"strIngredient1": "Sherry",
"strIngredient2": "Light cream",
"strIngredient3": "Powdered sugar",
"strIngredient4": "Egg",
"strIngredient5": "Nutmeg",
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 1/2 oz cream ",
"strMeasure2": "2 tsp ",
"strMeasure3": "1 tsp ",
"strMeasure4": "1 whole ",
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2016-11-10 23:27:08"
},
{
"idDrink": "12256",
"strDrink": "Sol Y Sombra",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Ordinary Drink",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Brandy snifter",
"strInstructions": "Shake ingredients with ice, strain into a brandy snifter, and serve. (The English translation of the name of this drink is \"Sun and Shade\", and after sampling this drink, you'll understand why. Thanks, Kirby.)",
"strInstructionsES": None,
"strInstructionsDE": "Die Zutaten mit Eis schütteln, in ein Brandyglas abseihen und servieren. (Die englische Übersetzung des Namens dieses Getränks lautet \"Sonne und Schatten\", und nachdem Sie dieses Getränk probiert haben, werden Sie verstehen, warum. Danke, Kirby.)",
"strInstructionsFR": None,
"strInstructionsIT": "Shakerare gli ingredienti con ghiaccio, filtrare in un bicchierino di brandy e servire.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/3gz2vw1503425983.jpg",
"strIngredient1": "Brandy",
"strIngredient2": "Anisette",
"strIngredient3": None,
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 1/2 oz ",
"strMeasure2": "1 1/2 oz ",
"strMeasure3": None,
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-08-22 19:19:43"
},
{
"idDrink": "16273",
"strDrink": "Shark Attack",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Cocktail",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Pitcher",
"strInstructions": "Mix lemonade and water according to instructions on back of can. If the instructions say to add 4 1/3 cans of water do so. Mix into pitcher. Add 1 1/2 cup of Vodka (Absolut). Mix well. Pour into glass of crushed ice. Excellent!",
"strInstructionsES": None,
"strInstructionsDE": "Limonade und Wasser nach Anleitung auf dem Dosenrücken mischen. Wenn die Anweisungen besagen, 4 1/3 Dosen Wasser hinzuzufügen, tun Sie dies. In den Krug mischen. Füge 1 1/2 Tasse Wodka (Absolut) hinzu. Gut mischen. In ein Glas zerstoßenes Eis gießen. Ausgezeichnet!",
"strInstructionsFR": None,
"strInstructionsIT": "Mescola la limonata e l'acqua.\r\nAggiungi 1 tazza e mezza di Vodka (Absolut).\r\nMescolare bene.\r\nVersare in un bicchiere di ghiaccio tritato.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/uv96zr1504793256.jpg",
"strIngredient1": "Lemonade",
"strIngredient2": "Water",
"strIngredient3": "Vodka",
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 can ",
"strMeasure2": "3 cans ",
"strMeasure3": "1 1/2 cup ",
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-09-07 15:07:37"
},
{
"idDrink": "15184",
"strDrink": "San Francisco",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Ordinary Drink",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Highball glass",
"strInstructions": "Take a tall glass and put in a few ice cubes, fill the vodka over it and fill with juice then the \"creme\", to end fill in the grenadine but very carefully at the side of the glass so it will lay down in the bottom. garnish with orange and strawberry.",
"strInstructionsES": None,
"strInstructionsDE": "Nimm ein hohes Glas und lege ein paar Eiswürfel hinein, fülle den Wodka darüber und fülle ihn mit Saft, dann die \"Creme\", um die Grenadine einzufüllen, aber sehr vorsichtig an der Seite des Glases, damit sie sich am Boden niederlässt. Garniere mit Orange und Erdbeere.",
"strInstructionsFR": None,
"strInstructionsIT": "Prendete un bicchiere alto e mettete qualche cubetto di ghiaccio, riempiteci sopra la vodka e riempite con il succo poi la \"crema\", per finire riempite la granatina ma con molta attenzione a lato del bicchiere in modo che si adagi sul fondo .\r\nGuarnire con arancia e fragola.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/szmj2d1504889961.jpg",
"strIngredient1": "Vodka",
"strIngredient2": "Creme de Banane",
"strIngredient3": "Grenadine",
"strIngredient4": "Orange juice",
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "2 cl ",
"strMeasure2": "2 cl ",
"strMeasure3": None,
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-09-08 17:59:21"
},
{
"idDrink": "15226",
"strDrink": "Space Odyssey",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Ordinary Drink",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Highball glass",
"strInstructions": "Fill glass with ice and add shots of Bacardi and Malibu. Add splash of pineapple juice and top with orange juice. Add grenadine for color and garnish with cherries.",
"strInstructionsES": None,
"strInstructionsDE": "Füllen Sie das Glas mit Eis und fügen Sie Spritzer von Bacardi und Malibu hinzu. Einen Spritzer Ananassaft dazugeben und mit Orangensaft auffüllen. Grenadine als Farbstoff beigeben und mit Kirschen garnieren.",
"strInstructionsFR": None,
"strInstructionsIT": "Riempi il bicchiere con ghiaccio e aggiungi in dei bicchieri un pò di Bacardi e Malibu.\r\nAggiungere una spruzzata di succo d'ananas e guarnire con succo d'arancia.\r\nAggiungere la granatina per colorare e guarnire con le ciliegie.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vxtjbx1504817842.jpg",
"strIngredient1": "151 proof rum",
"strIngredient2": "Malibu rum",
"strIngredient3": "Pineapple juice",
"strIngredient4": "Orange juice",
"strIngredient5": "Grenadine",
"strIngredient6": "Cherries",
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 shot Bacardi ",
"strMeasure2": "1 shot ",
"strMeasure3": "1 shot ",
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-09-07 21:57:23"
},
{
"idDrink": "12188",
"strDrink": "Sherry Eggnog",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Ordinary Drink",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Collins glass",
"strInstructions": "Shake sherry, powdered sugar, and egg with ice and strain into a collins glass. Fill with milk and stir. Sprinkle nutmeg on top and serve.",
"strInstructionsES": None,
"strInstructionsDE": "Sherry, Puderzucker und Ei mit Eis schütteln und in ein Collins-Glas abseihen. Mit Milch füllen und umrühren. Muskatnuss darüber streuen und servieren.",
"strInstructionsFR": None,
"strInstructionsIT": "Shakerare lo sherry, lo zucchero a velo e l'uovo con ghiaccio e filtrare in un bicchiere Collins.Riempi di latte e mescola.Cospargere di noce moscata e servire.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xwrpsv1478820541.jpg",
"strIngredient1": "Sherry",
"strIngredient2": "Powdered sugar",
"strIngredient3": "Egg",
"strIngredient4": "Milk",
"strIngredient5": "Nutmeg",
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "2 oz cream ",
"strMeasure2": "1 tsp ",
"strMeasure3": "1 whole ",
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2016-11-10 23:29:01"
},
{
"idDrink": "12724",
"strDrink": "Sweet Bananas",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Shake",
"strIBA": None,
"strAlcoholic": "Non alcoholic",
"strGlass": "Highball Glass",
"strInstructions": "Place all ingredients in the blender jar - cover and whiz on medium speed until well blended. Pour in one tall, 2 medium or 3 small glasses and drink up.",
"strInstructionsES": None,
"strInstructionsDE": "Alle Zutaten in den Mixer geben - abdecken und bei mittlerer Geschwindigkeit schaumig schlagen, bis sie gut vermischt sind. In ein großes, 2 mittlere oder 3 kleine Gläser füllen und geniessen.",
"strInstructionsFR": None,
"strInstructionsIT": "Mettere tutti gli ingredienti nella caraffa del frullatore - coprire e montare a velocità media fino a quando non sono ben amalgamati.Versare in un bicchiere alto, 2 medi o 3 piccoli e bere.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/sxpcj71487603345.jpg",
"strIngredient1": "Milk",
"strIngredient2": "Banana",
"strIngredient3": "Honey",
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "2 cups ",
"strMeasure2": "1 ",
"strMeasure3": "1 tblsp ",
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-02-20 15:09:05"
},
{
"idDrink": "13024",
"strDrink": "Sweet Sangria",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Punch / Party Drink",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Pitcher",
"strInstructions": "Dissolve the sugar in hot water and cool. Peel the citrus fruits and break into wedges. Mix the wine, sugar syrup, fruit, and Fresca in a pitcher and put in the fridge for a few hours. Serve in tall glasses with a straw.",
"strInstructionsES": None,
"strInstructionsDE": "Den Zucker in heißem Wasser auflösen und abkühlen lassen. Die Zitrusfrüchte schälen und stückeln. Wein, Zuckersirup, Obst und Fresca in einem Krug mischen und für einige Stunden in den Kühlschrank stellen. In hohen Gläsern mit einem Strohhalm servieren.",
"strInstructionsFR": None,
"strInstructionsIT": "Sciogliere lo zucchero in acqua calda e raffreddare.\r\nPelare gli agrumi e spezzarli a spicchi.\r\nMescolare il vino, lo sciroppo di zucchero, la frutta e la Fresca in una caraffa e mettere in frigo per qualche ora.\r\nServire in bicchieri alti con una cannuccia.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/uqqvsp1468924228.jpg",
"strIngredient1": "Red wine",
"strIngredient2": "Sugar",
"strIngredient3": "Water",
"strIngredient4": "Apple",
"strIngredient5": "Orange",
"strIngredient6": "Lime",
"strIngredient7": "Lemon",
"strIngredient8": "Fresca",
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "2 bottles ",
"strMeasure2": "1 cup ",
"strMeasure3": "2 cups hot ",
"strMeasure4": "1 cup",
"strMeasure5": " wedges\n",
"strMeasure6": " wedges\n",
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2016-07-19 11:30:28"
},
{
"idDrink": "12388",
"strDrink": "Thriller",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Ordinary Drink",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Cocktail glass",
"strInstructions": "In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.",
"strInstructionsES": None,
"strInstructionsDE": "In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Cocktailglas abseihen.",
"strInstructionsFR": None,
"strInstructionsIT": "In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Agitare bene.Filtrare in un bicchiere da cocktail.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/rvuswq1461867714.jpg",
"strIngredient1": "Scotch",
"strIngredient2": "Wine",
"strIngredient3": "Orange juice",
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 1/2 oz ",
"strMeasure2": "1 oz Green Ginger ",
"strMeasure3": "1 oz ",
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2016-04-28 19:21:54"
},
{
"idDrink": "178350",
"strDrink": "The Galah",
"strDrinkAlternate": None,
"strTags": "Dark",
"strVideo": None,
"strCategory": "Cocktail",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Collins glass",
"strInstructions": "Mix together the alcoholic portions and top with Pineapple and Lime juice.",
"strInstructionsES": None,
"strInstructionsDE": None,
"strInstructionsFR": None,
"strInstructionsIT": None,
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/sy7y6r1614775067.jpg",
"strIngredient1": "Dark Rum",
"strIngredient2": "Campari",
"strIngredient3": "Creme De Banane",
"strIngredient4": "Pineapple Juice",
"strIngredient5": "Lime Juice",
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 shot",
"strMeasure2": "1 shot",
"strMeasure3": "1/2 shot",
"strMeasure4": "Top",
"strMeasure5": "Top",
"strMeasure6": "",
"strMeasure7": "",
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": "https://www.instagram.com/p/CLFp5hqlYZC/",
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": None
},
{
"idDrink": "12856",
"strDrink": "Tia-Maria",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Homemade Liqueur",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Collins Glass",
"strInstructions": "Boil water, sugar and coffe for 10 mins and let cool. Add rum and vanilla. Put in clean bottle(s) and leave for 1 week before using.",
"strInstructionsES": None,
"strInstructionsDE": "Wasser, Zucker und Kaffee 10 Minuten lang kochen und abkühlen lassen. Rum und Vanille dazugeben. In saubere Flasche(n) geben und vor Gebrauch 1 Woche ruhen lassen.",
"strInstructionsFR": None,
"strInstructionsIT": "Far bollire l'acqua, lo zucchero e il caffè per 10 minuti e lasciar raffreddare. Aggiungi rum e vaniglia. Mettere in bottiglie pulite e lasciare agire per 1 settimana prima dell'uso.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/sih81u1504367097.jpg",
"strIngredient1": "Water",
"strIngredient2": "Brown sugar",
"strIngredient3": "Coffee",
"strIngredient4": "Rum",
"strIngredient5": "Vanilla extract",
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 cup ",
"strMeasure2": "3/4-1 cup ",
"strMeasure3": "4 tsp ",
"strMeasure4": "1 cup ",
"strMeasure5": "4 tsp ",
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-09-02 16:44:58"
},
{
"idDrink": "17828",
"strDrink": "Tipperary",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Cocktail",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Nick and Nora Glass",
"strInstructions": "Stir over ice. Strain into chilled glass. Cut a wide swath of orange peel, and express the orange oils over the drink. Discard orange twist.",
"strInstructionsES": None,
"strInstructionsDE": "Über das Eis geben. In ein gekühltes Glas abseihen. Schneiden Sie einen breiten Streifen Orangenschale und geben Sie die Orangenöle über das Getränk. Entsorgen Sie den orangefarbenen Twist.",
"strInstructionsFR": None,
"strInstructionsIT": "Mescola sul ghiaccio.\r\nFiltrare in un bicchiere freddo.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/b522ek1521761610.jpg",
"strIngredient1": "Irish Whiskey",
"strIngredient2": "Sweet Vermouth",
"strIngredient3": "Green Chartreuse",
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "2 oz",
"strMeasure2": "1 oz",
"strMeasure3": "1/2 oz",
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2018-03-22 23:33:30"
},
{
"idDrink": "15006",
"strDrink": "Turkeyball",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Shot",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Shot glass",
"strInstructions": "Shake with ice and strain into a shot glass.",
"strInstructionsES": None,
"strInstructionsDE": "Mit Eis schütteln und in ein Schnapsglas abseihen.",
"strInstructionsFR": None,
"strInstructionsIT": "Shakerare con ghiaccio e filtra in un bicchiere da shot",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/rxurpr1441554292.jpg",
"strIngredient1": "Wild Turkey",
"strIngredient2": "Amaretto",
"strIngredient3": "Pineapple juice",
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1 oz ",
"strMeasure2": "3/4 oz ",
"strMeasure3": "1 splash ",
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2015-09-06 16:44:53"
},
{
"idDrink": "15639",
"strDrink": "Texas Sling",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Shake",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Wine Glass",
"strInstructions": "Blend with Ice until smooth. Serve in a tulip glass, top with whip cream.",
"strInstructionsES": None,
"strInstructionsDE": "Mit Eis mischen, bis es glatt ist. In einem Tulpenglas servieren, mit Schlagsahne bedecken.",
"strInstructionsFR": None,
"strInstructionsIT": "Frullare con ghiaccio fino a che liscio.\r\nServire in un bicchiere a tulipano, guarnire con panna montata.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/ypl13s1504890158.jpg",
"strIngredient1": "Kahlua",
"strIngredient2": "Irish cream",
"strIngredient3": "Amaretto",
"strIngredient4": "151 proof rum",
"strIngredient5": "Cream",
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "1/2 oz ",
"strMeasure2": "1/2 oz ",
"strMeasure3": "1/2 oz ",
"strMeasure4": "1/2 oz Bacardi ",
"strMeasure5": "1 oz ",
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-09-08 18:02:39"
},
{
"idDrink": "12782",
"strDrink": "Thai Coffee",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Coffee / Tea",
"strIBA": None,
"strAlcoholic": "Non alcoholic",
"strGlass": "Highball glass",
"strInstructions": "Place the coffee and spices in the filter cone of your coffee maker. Brew coffee as usual, let it cool. In a tall glass, dissolve 1 or 2 teaspoons of sugar in an ounce of the coffee (it's easier to dissolve than if you put it right over ice). Add 5-6 ice cubes and pour coffee to within about 1 inch of the top of the glass. Rest a spoon on top of the coffee and slowly pour whipping cream into the spoon. This will make the cream float on top of the coffee rather than dispersing into it right away.",
"strInstructionsES": None,
"strInstructionsDE": "Geben Sie den Kaffee und die Gewürze in den Filterkegel Ihrer Kaffeemaschine. Kaffee wie gewohnt zubereiten, abkühlen lassen. In einem hohen Glas 1 oder 2 Teelöffel Zucker in 2 Esslöffel Kaffee auflösen (es ist einfacher zu lösen, als wenn man ihn direkt auf Eis legt). Füge 5-6 Eiswürfel hinzu und gieße Kaffee 2-3cm von der Oberseite des Glases auf. Einen Löffel auf den Kaffee legen und langsam Schlagsahne in den Löffel geben. Dadurch wird die Creme auf dem Kaffee schweben, anstatt sich sofort darin zu verteilen.",
"strInstructionsFR": None,
"strInstructionsIT": "Metti il caffè e le spezie nel cono del filtro della tua caffettiera.\r\nPrepara il caffè come al solito, lascialo raffreddare.\r\nIn un bicchiere alto, sciogli 1 o 2 cucchiaini di zucchero in 30gr di caffè (è più facile da sciogliere che se lo metti sul ghiaccio).\r\nAggiungere 5-6 cubetti di ghiaccio e versare il caffè a circa 1 pollice dalla parte superiore del bicchiere.\r\nAppoggia un cucchiaio sopra il caffè e versa lentamente la panna montata nel cucchiaio.\r\nIn questo modo la crema galleggerà sul caffè anziché disperdersi subito.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/wquwxs1441247025.jpg",
"strIngredient1": "Coffee",
"strIngredient2": "Coriander",
"strIngredient3": "Cardamom",
"strIngredient4": "Sugar",
"strIngredient5": "Whipping cream",
"strIngredient6": "Ice",
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "6 tblsp ground",
"strMeasure2": "1/4 tsp ",
"strMeasure3": "4-5 whole green ",
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2015-09-03 03:23:45"
},
{
"idDrink": "12402",
"strDrink": "Tom Collins",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Ordinary Drink",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Collins glass",
"strInstructions": "In a shaker half-filled with ice cubes, combine the gin, lemon juice, and sugar. Shake well. Strain into a collins glass alomst filled with ice cubes. Add the club soda. Stir and garnish with the cherry and the orange slice.",
"strInstructionsES": None,
"strInstructionsDE": "In einem Shaker, der halb mit Eiswürfeln gefüllt ist, Gin, Zitronensaft und Zucker mischen. Gut schütteln. In ein Collins-Glas abseihen, das mit Eiswürfeln gefüllt ist. Füge das Club-Soda hinzu. Umrühren und mit der Kirsche und der Orangenscheibe garnieren.",
"strInstructionsFR": None,
"strInstructionsIT": "In uno shaker riempito a metà con cubetti di ghiaccio, unisci il gin, il succo di limone e lo zucchero.Mescolate e guarnite con la ciliegia e la fetta d'arancia.Filtrare in un bicchiere collins pieno di cubetti di ghiaccio.Aggiungi la soda club.Agitare bene.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/7cll921606854636.jpg",
"strIngredient1": "Gin",
"strIngredient2": "Lemon juice",
"strIngredient3": "Sugar",
"strIngredient4": "Club soda",
"strIngredient5": "Maraschino cherry",
"strIngredient6": "Orange",
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "2 oz ",
"strMeasure2": "1 oz ",
"strMeasure3": "1 tsp superfine ",
"strMeasure4": "3 oz ",
"strMeasure5": "1 ",
"strMeasure6": "1 ",
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": "https://commons.wikimedia.org/wiki/File:Tom_Collins.jpg",
"strImageAttribution": "Will Shenton",
"strCreativeCommonsConfirmed": "Yes",
"dateModified": "2015-08-18 15:21:22"
},
{
"idDrink": "12726",
"strDrink": "Tomato Tang",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Other / Unknown",
"strIBA": None,
"strAlcoholic": "Non alcoholic",
"strGlass": "Highball glass",
"strInstructions": "Place all ingredients in the blender jar - cover and whiz on medium speed until well blended. Pour in one tall, 2 medium or 3 small glasses and drink up.",
"strInstructionsES": None,
"strInstructionsDE": "Alle Zutaten in den Mixer geben - abdecken und bei mittlerer Geschwindigkeit schaumig schlagen, bis sie gut vermischt sind. In ein großes, 2 mittlere oder 3 kleine Gläser füllen und geniessen.",
"strInstructionsFR": None,
"strInstructionsIT": "Mettere tutti gli ingredienti nella caraffa del frullatore - coprire e montare a velocità media fino a quando non sono ben amalgamati.Versare in un bicchiere alto, 2 medi o 3 piccoli e bere.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/869qr81487603278.jpg",
"strIngredient1": "Tomato juice",
"strIngredient2": "Lemon juice",
"strIngredient3": "Celery salt",
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "2 cups ",
"strMeasure2": "1-2 tblsp ",
"strMeasure3": "1 dash ",
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-02-20 15:07:58"
},
{
"idDrink": "14860",
"strDrink": "Talos Coffee",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Coffee / Tea",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Brandy snifter",
"strInstructions": "Add your GM and then add your coffee.",
"strInstructionsES": None,
"strInstructionsDE": "Füge deinen GM und dann deinen Kaffee hinzu.",
"strInstructionsFR": None,
"strInstructionsIT": "Aggiungi il Grand Marnier e poi aggiungi il tuo caffè.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/rswqpy1441246518.jpg",
"strIngredient1": "Grand Marnier",
"strIngredient2": "Coffee",
"strIngredient3": None,
"strIngredient4": None,
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "3 parts ",
"strMeasure2": "1 part ",
"strMeasure3": None,
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2015-09-03 03:15:18"
},
{
"idDrink": "15515",
"strDrink": "Tennesee Mud",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Coffee / Tea",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Coffee Mug",
"strInstructions": "Mix Coffee, Jack Daniels and Amaretto. Add Cream on top.",
"strInstructionsES": None,
"strInstructionsDE": "Mische Kaffee, Jack Daniels und Amaretto. Creme darauf geben.",
"strInstructionsFR": None,
"strInstructionsIT": "Mescola il caffè, Jack Daniels e Amaretto. Aggiungi la panna sopra.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/txruqv1441245770.jpg",
"strIngredient1": "Coffee",
"strIngredient2": "Jack Daniels",
"strIngredient3": "Amaretto",
"strIngredient4": "Whipped cream",
"strIngredient5": None,
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "8 oz ",
"strMeasure2": "4 oz ",
"strMeasure3": "4 oz ",
"strMeasure4": None,
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2015-09-03 03:02:50"
},
{
"idDrink": "12362",
"strDrink": "Tequila Fizz",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Ordinary Drink",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Collins glass",
"strInstructions": "Shake all ingredients (except ginger ale) with ice and strain into a collins glass over ice cubes. Fill with ginger ale, stir, and serve.",
"strInstructionsES": None,
"strInstructionsDE": "Alle Zutaten (außer Ginger Ale) mit Eis schütteln und in ein Collins-Glas über Eiswürfel abseihen. Mit Ginger Ale füllen, umrühren und servieren.",
"strInstructionsFR": None,
"strInstructionsIT": "Shakerare tutti gli ingredienti (eccetto ginger ale) con ghiaccio e filtrare in un bicchiere Collins con cubetti di ghiaccio.Riempi con ginger ale, mescola e servi.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/2bcase1504889637.jpg",
"strIngredient1": "Tequila",
"strIngredient2": "Lemon juice",
"strIngredient3": "Grenadine",
"strIngredient4": "Egg white",
"strIngredient5": "Ginger ale",
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "2 oz ",
"strMeasure2": "1 tblsp ",
"strMeasure3": "3/4 oz ",
"strMeasure4": "1 ",
"strMeasure5": None,
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-09-08 17:53:57"
},
{
"idDrink": "12370",
"strDrink": "Tequila Sour",
"strDrinkAlternate": None,
"strTags": None,
"strVideo": None,
"strCategory": "Ordinary Drink",
"strIBA": None,
"strAlcoholic": "Alcoholic",
"strGlass": "Whiskey sour glass",
"strInstructions": "Shake tequila, juice of lemon, and powdered sugar with ice and strain into a whiskey sour glass. Add the half-slice of lemon, top with the cherry, and serve.",
"strInstructionsES": None,
"strInstructionsDE": "Tequila, Zitronensaft und Puderzucker mit Eis schütteln und in ein Whiskey-Sourglas abseihen. Die halbe Zitronenscheibe dazugeben, mit der Kirsche garnieren und servieren.",
"strInstructionsFR": None,
"strInstructionsIT": "Shakerare la tequila, il succo di limone e lo zucchero a velo con ghiaccio e filtrare in un bicchiere da whisky sour.Aggiungere la mezza fetta di limone, guarnire con la ciliegia e servire.",
"strInstructionsZH-HANS": None,
"strInstructionsZH-HANT": None,
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/ek0mlq1504820601.jpg",
"strIngredient1": "Tequila",
"strIngredient2": "Lemon",
"strIngredient3": "Powdered sugar",
"strIngredient4": "Lemon",
"strIngredient5": "Cherry",
"strIngredient6": None,
"strIngredient7": None,
"strIngredient8": None,
"strIngredient9": None,
"strIngredient10": None,
"strIngredient11": None,
"strIngredient12": None,
"strIngredient13": None,
"strIngredient14": None,
"strIngredient15": None,
"strMeasure1": "2 oz ",
"strMeasure2": "Juice of 1/2 ",
"strMeasure3": "1 tsp ",
"strMeasure4": "1/2 slice ",
"strMeasure5": "1 ",
"strMeasure6": None,
"strMeasure7": None,
"strMeasure8": None,
"strMeasure9": None,
"strMeasure10": None,
"strMeasure11": None,
"strMeasure12": None,
"strMeasure13": None,
"strMeasure14": None,
"strMeasure15": None,
"strImageSource": None,
"strImageAttribution": None,
"strCreativeCommonsConfirmed": "No",
"dateModified": "2017-09-07 22:43:21"
},
      ]
}



# Loop through each drink in the "drinks" list
for drink in data["drinks"]:
    # Create a new dictionary for the transformed data
    transformed_drink = {
        "name": drink["strDrink"],
        "category": drink["strCategory"],
        "alcoholic": True if drink["strAlcoholic"].lower() == "alcoholic" else False,
        "glass": drink["strGlass"],
        "instructions": drink["strInstructions"],
        "picture": drink["strDrinkThumb"],
        "ingredients": []
    }

    # Loop through ingredients and add them to the "ingredients" list
    for i in range(1, 16):
        ingredient_key = f"strIngredient{i}"
        measure_key = f"strMeasure{i}"
        ingredient = drink.get(ingredient_key)
        measure = drink.get(measure_key)

        if ingredient:
            transformed_drink["ingredients"].append({
                "ingredient": ingredient,
                "measure": measure if measure else ""
            })

    # Append the transformed drink to the list
    transformed_data.append(transformed_drink)

# Create a new dictionary with the "drinks" key and the transformed data
transformed_json = {"drinks": transformed_data}

# Convert the dictionary to a JSON string
formatted_json = json.dumps(transformed_json, indent=2)

# Print the formatted JSON
print(formatted_json)